# -*- coding: utf-8 -*-
"""Conditional Statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lmim5j1rP5hy__Ba7KabKVd053jHAOEo
"""

Conditional Statement
1.if Statement
2.if-else Statement
3.elif Statement
4.break Statement
5.Continue Statement

"""# if_Statement

synatax:-
  if condition:-
     statement 1:
     statement 2:
"""

a=250
b=300

if b>a:
  print(f'b is greather value is a')

a=int(input("Enter the value"))
b=int(input("Enter the value"))

if b>a:
  print(f"b is greather the value is a")

a=250
b=300

if a<b:
  print(f'a is lessthan value is b')

# if_else_Statement:
#syntax:-

  if conditions:
      statement 1
  else:
      other statement 2

age=25
if age>35:
  print(f'you are eligiable the vote:')
else:
  print(f'you are not eligiable the vote:')

age=int(input("Enter the age:"))

if age>45:
  print(f'you are eligiable the vote:')
else:
  print(f'you are not eligiable the vote:')

a=2500
b=3000

if b>a:
  print(f'b is greather the value is a')
else:
  print(f'a is highest value :')

"""# elif_Statement

 syntax:-

   if conditions1:
      statement1

   if_else conditions2:
       statement2  

   elif_else conditions3:
        statement3     
"""

# elif_else_Statement
a=3500
b=3000
c=5000

if a>b:
  print(f'b is greather the value is a:')
elif b>c:
  print(f'b is grether the  value is c:')
else:
  print(f' c is highest value')

a=int(input("Enter  a the value:"))
b=int(input("Enter b the value:"))
c=int(input("Enter c the value:"))

if (a>b) and (b>c):
  print(f'maxmum value is :',a)
elif (b>a) and (b>c):
  print(f' maxmium value is :',b)
else:
  print(f'maxmum value is :',c)

money=10000
iphone=45000
samsung=35000
vivo=15000

if money>iphone:
  print('i will buy iphone')
elif iphone> samsung:
  print('i will buy samsung')
elif samsung>money:
  print('i will buy vivo ')
else:
  print('Money not sufficient')

